### ISSUE TITLE
Supertux: Rapid (potentially seizure inducing) resizing caused by sdl2-compat emitting erroneous resize events

### ISSUE THREAD

**Issue by tulpenkiste** [libsdl-org/sdl2-compat#231]
Supertux continously receives event 200, with window event type alternating between values 3, 5 and 6.
Only occurs with sdl2-compat, sdl2 itself works fine.

https://github.com/user-attachments/assets/8c419c2f-1e44-4660-820f-d611e60f6f8a

**Comment by Kontrabant** [comment]
Ah, the issue is that SDL2 isn't flushing old size events from the translated event queue as native SDL2 and SDL3 do. SuperTux redundantly calls `SDL_SetWindowSize()` after every size event, and in cases where the underlying desktop sends multiple resize events, the most recent is being overwritten with old data in a feedback loop.

**Comment by slouken** [comment]
I think @Kontrabant has already taken care of this in sdl2-compat.

**Comment by Kontrabant** [comment]
Yes, sdl2-compat now matches the behavior of SDL2, so the issue is fixed.
